version: '3'
services:
  gitlab-api-extender:
    image: phoenixsystemsag/gitlab-api-extender:latest
    restart: unless-stopped
    ports:
      - 80
    environment:
      - "App__Access__Key=<api-access-key>"
      - "App__GitLab__Url=<gitlab-api-url>"
      - "App__GitLab__Token=<gitlab-token>"
